---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   labels:
      run: nginx
   name: nginx
spec:
   replicas: 2
   selector:
     matchLabels:
       run: nginx
   template:
     metadata:
        labels:
          run: nginx
     spec:
        containers:
          - image: cssp007143/nginx-image
            name:  nginx
            
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - nodePort: 30303
      port: 80
      targetPort: 80
  selector:
    name: nginx
