---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: harbor.cssp.tech/production/nginx-image:${build_number}
    ports:
    - containerPort: 80
  imagePullSecrets:
    - name: regcred
            
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - nodePort: 30303
      port: 80
      targetPort: 80
  selector:
    run: nginx
